metadata:
  name: "deny-privileged-profile"
  annotations:
    policies.kyverno.io/category: "Velero"
    policies.kyverno.io/description: "The ':stable' tag is mutable and can lead to\
      \ unexpected errors if the image changes.  A best practice is to use an immutable\
      \ tag (e.g. v2.3) that maps to a specific version  of an application pod."
apiVersion: "kyverno.io/v1"
kind: "ClusterPolicy"    
spec:
  validationFailureAction: audit
  background: false
  rules:
  - name: check-privileged
    match:
      any:
      - resources:
          kinds:
            - Namespace
          selector:
            matchLabels:
              pod-security.kubernetes.io/enforce: privileged
    exclude:
      any:
      - clusterRoles:
        - cluster-admin
    validate:
      message: Only cluster-admins may create Namespaces that allow setting the privileged level.
      deny: {}

